### PR TITLE
catch exceptions thrown by service implementation

### LINKED ISSUE #18: make sure that ServiceAdapter catches exceptions
we want to make sure that we handle exceptions thrown by user-supplied code, not just failed Futures

### PR DESCRIPTION
**Pull request by ccmtaylor**
we want to make sure to catch exceptions thrown by
user implementations of the generated service
interface. We do this by wrapping them in
`Service.rescue()`.

Refactors `ServiceAdapter` to be a `Filter`, since it
really is one.

Fixes #18.

### CODE REVIEW

**Comment by dziemba** [comment]
Can we add a test for this?

File: runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    val (_, svc) = builder.build(
+      oops,
+      EndpointMetadata("/twirp", "service", "rpc")
+    )
+
+    val request = Request()
+    request.mediaType = MediaType.Json
+    request.contentString = "{}"
+
+    Await.result(svc(request).liftToTry) must not throwAn(ex)
```
Comment (dziemba) [inline runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala]: You could also just do `Await.ready` without the `liftToTry` (just for clarity: it took me a while to realize that this variant actually works as expected, too)

Comment (dziemba) [reply runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala]: `throwAn(ex)` but `ex` is never used anywhere? I'm not sure I get that part. I guess you can just remove the whole `must not throw` part, since throwing anything will automatically fail the test anyway

Comment (dziemba) [reply runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala]: Also, I'd probably use `throwA[Exception]`, it's not immediately clear that `throwAn(ex)` just compares the type, not the exception or message itself. Or just remove the whole `must not throw` part, since a throw will fail the test automatically anway.

Comment (dziemba) [inline runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala]: How about `Await.result(svc(request).liftToTry).isThrow ==== true`? Then we don't need the awkward `throwAn(ex)` matcher and also ensure that the exception is actually wrapped inside the Future.

Comment (ccmtaylor) [reply runtime/src/test/scala/com/soundcloud/twinagle/ServerEndpointBuilderSpec.scala]: ah whoops. `ex` is a leftover from a refactoring. I agree it's confusing this way
